# Generated by Django 4.1.7 on 2023-09-01 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registration_creationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('pertime', models.CharField(blank=True, max_length=200, null=True)),
                ('cooktime', models.CharField(blank=True, max_length=200, null=True)),
                ('yields', models.CharField(blank=True, max_length=200, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.FileField(blank=True, max_length=200, null=True, upload_to='')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registration')),
            ],
        ),
    ]
