# Generated by Django 4.1.7 on 2023-09-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_comment_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waiting For Approval'), (2, 'Approval'), (3, 'Rejected')], default=1),
        ),
    ]
