# Generated by Django 4.0.2 on 2023-09-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Waiting For Approval'), (2, 'Approval'), (3, 'Rejected')], default=1, null=True),
        ),
    ]
