# Generated by Django 4.0.2 on 2023-09-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
